#pragma once
#define MASTER_LEFT
#define QUICK_TAP_TERM 0
#define TAPPING_TERM 300
#define IGNORE_MOD_TAP_INTERRUPT
#define DYNAMIC_TAPPING_TERM_ENABLE
#define DYNAMIC_TAPPING_TERM_INCREMENT 20
#define DYNAMIC_TAPPING_TERM_MAX 500
#define DYNAMIC_TAPPING_TERM_MIN 100
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
